defaults:
 - base
 - _self_

data:
  task: hallucination
  dataset: pdb
  all_angles: False
  sampler:
    max_batch_size: 64
    max_num_res_squared: 400_000

model:
  aatype_pred_num_tokens: 20
  transformer_dropout: 0.2
  net_type: frameflow
  rigids_scaling: True
  llm:
    use: True
    name: esm2_t33_650M_UR50D
    sample_deterministic: True
    cfg:
      d_model: ${model.node_embed_size}
      n_enc_layers: 3
      n_dec_layers: 3
      dropout: 0.2

interpolant:
  codesign_separate_t: True
  aatypes:
    corrupt: True
    temp: 0.1
    do_purity: True
    noise: 20.0
    interpolant_type: masking
  angles:
    corrupt: True
    sample_schedule: exp
    do_purify: False

experiment:
  debug: False
  raw_state_dict_reload: null
  training:
    aatypes_loss_weight: 1.0
    aatypes_loss_llm_weight: 1.0
    translation_loss_weight: 2.0
    rotation_loss_weights: 1.0
    torsion_loss_weight: 0.1
    aux_loss_weight: 0.0
  num_devices: 8   # number of gpus
  warm_start: null
  wandb:
    name: codesign_${data.dataset}
  trainer:
    check_val_every_n_epoch: 6
    accumulate_grad_batches: 2
  checkpointer:
    save_top_k: -1
    every_n_epochs: 50
    save_on_train_epoch_end: True
    monitor: null
